# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('pub_data', models.DateField(verbose_name='出版日期')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读数量')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
